#!/bin/bash

CONTAINER_NAME="stingray_control"

# Проверяем, запущен ли контейнер с данным именем
RUNNING_CONTAINER=$(docker ps -q -f name="${CONTAINER_NAME}")

if [ -n "$RUNNING_CONTAINER" ]; then
    echo "Контейнер ${CONTAINER_NAME} уже запущен. Подключаемся к нему..."
    docker exec -it "${CONTAINER_NAME}" bash
    exit 0
fi

# Если контейнер с таким именем не запущен, то проверяем,
# возможно он есть, но остановлен:
STOPPED_CONTAINER=$(docker ps -aq -f name="${CONTAINER_NAME}")
if [ -n "$STOPPED_CONTAINER" ]; then
    echo "Контейнер ${CONTAINER_NAME} найден, но не запущен. Запускаем..."
    docker start "${CONTAINER_NAME}"
    # Далее заходим в bash контейнера:
    docker exec -it "${CONTAINER_NAME}" bash
    exit 0
fi

echo "Контейнер ${CONTAINER_NAME} не найден. Создаём и запускаем новый..."

# На хосте разрешите X11 соединения
xhost +local:docker

# Запускаем новый контейнер в интерактивном режиме
docker run -it --rm \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --device=/dev/dri:/dev/dri \
    --name "${CONTAINER_NAME}" \
    --mount type=bind,source="/etc/timezone",target="/etc/timezone" \
    --mount type=bind,source="/etc/localtime",target="/etc/localtime" \
    --ipc=host \
    --net=host \
    hydronautics/stingray:control bash
