nodes:
    object_detection: yolo_detector
topics:
    to_driver_parcel: "/stingray/topics/to_driver_parcel"
    from_driver_parcel: "/stingray/topics/from_driver_parcel"
    robot_info: "/stingray/topics/driver/robot_info"
    depth: "/stingray/topics/position/depth"
    yaw: "/stingray/topics/position/yaw"
    pinger_buckets: "/stingray/topics/position/pinger_buckets"
    pinger_flare: "/stingray/topics/position/pinger_flare"
    gazebo_velocity: "/cmd_vel"
    gazebo_odometry: "/odom"
    marker: "/marker_box"
services:
    stingray_missions:
        transition: "/stingray/services/missions/transition"
    set_horizontal_move: "/stingray/services/control/set_horizontal_move"
    set_depth: "/stingray/services/control/set_depth"
    set_yaw: "/stingray/services/control/set_yaw"
    set_imu_enabled: "/stingray/services/control/set_imu_enabled"
    set_stabilization_enabled: "/stingray/services/control/set_stabilization"
    set_device: "/stingray/services/control/set_device"
    gazebo_get_state: "/gazebo/get_model_state"
    gazebo_set_state: "/gazebo/set_model_state"
    set_enable_object_detection: "/stingray/services/vision/set_enable_object_detection"
    updown: "/stingray/services/devices/updown"
    set_enable_marker: "/marker_detection_switch"
actions:
    movement:
        horizontal: "/stingray/actions/movement/horizontal"
        dive: "/stingray/actions/movement/dive"
        align: "/stingray/actions/movement/align"
        align_low_level: "/stingray/actions/movement/align_low_level"
        tack: "/stingray/actions/movement/tack"
    updown: "/stingray/actions/devices/updown"
