initial_mission: INIT
missions:
  INIT:
    config_name: init
    package_name: stingray_missions
  SEARCH_VISION:
    config_name: search_vision
    package_name: stingray_missions
transitions:
  - { trigger: ok, source: INIT, dest: SEARCH_VISION }
  - { trigger: ok, source: SEARCH_VISION, dest: SUCCESS }
  - { trigger: timeout, source: [INIT, SEARCH_VISION], dest: FAILED }
  - { trigger: failed, source: [INIT, SEARCH_VISION], dest: FAILED }
