initial: INIT
missions:
  INIT:
    config_name: init
    package_name: stingray_missions
  END:
    config_name: end
    package_name: stingray_missions
transitions:
  - { source: INIT, outcome: OK, dest: END }
  - { source: END, outcome: OK, dest: OK }
  - { source: [INIT, END], outcome: FAILED, dest: FAILED }
