initial: START_VIDEO_RECORDING
ok_state_package_name: stingray_missions
failed_state_package_name: stingray_missions
chill_state_package_name: stingray_missions
missions:
  START_VIDEO_RECORDING:
    config_name: start_video_recording
    package_name: stingray_missions
  CHECK:
    config_name: check
    package_name: stingray_missions
transitions:
  - { source: START_VIDEO_RECORDING, outcome: OK, dest: CHECK }
  - { source: CHECK, outcome: OK, dest: IDLE }
  - { source: [START_VIDEO_RECORDING, CHECK], outcome: FAILED, dest: FAILED }
