initial_mission: INIT
missions:
  INIT:
    config: init
    package: stingray_missions
  SEARCH_VISION:
    config: search_vision
    package: stingray_missions
transitions:
  - { trigger: ok, source: INIT, dest: SEARCH_VISION }
  - { trigger: ok, source: SEARCH_VISION, dest: SUCCESS }
  - { trigger: timeout, source: [INIT, SEARCH_VISION], dest: FAILED }
  - { trigger: failed, source: [INIT, SEARCH_VISION], dest: FAILED }
