# Goal
uint8 DIRECTION_MARCH_FORWARD=1
uint8 DIRECTION_MARCH_BACKWARDS=2
uint8 DIRECTION_LAG_RIGHT=3
uint8 DIRECTION_LAG_LEFT=4
uint8 DIRECTION_STOP=0

# Direction, use constants
uint8 direction

# Velocity value from 0.0 to 1.0
float64 velocity

# Duration in milliseconds
uint32 duration
---
# Result
std_msgs/Empty empty
---
# Feedback
std_msgs/Empty empty