initial: DISABLE_STABILIZATION
states:
  DISABLE_STABILIZATION:
    action:
      type: EnableStabilization
      depth: false
      roll: false
      pitch: false
      yaw: false
  EMERGE:
    action: 
      type: Twist
      surge: 0.0
      sway: 0.0
      depth: -100.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
      duration: 15.0
transitions:
  - { trigger: ok, source: DISABLE_STABILIZATION, dest: EMERGE }
  - { trigger: ok, source: EMERGE, dest: OK }
  - { trigger: timeout, source: "*", dest: FAILED }
  - { trigger: fail, source: "*", dest: FAILED }
