initial: ROTATE_CLOCK
states:
  ROTATE_CLOCK:
    transition_event: 
      type: ObjectDetectionEvent
      topic_name: /stingray/topics/front_camera/bbox_array
      data: red_bowl
      count: 5
      trigger: found
    timeout: 60
    action: 
      type: Twist
      surge: 0.0
      sway: 0.0
      depth: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 15
  ROTATE_ANTICLOCK:
    transition_event: 
      type: ObjectDetectionEvent
      topic_name: /stingray/topics/front_camera/bbox_array
      data: red_bowl
      count: 5
      trigger: found
    timeout: 60
    action: 
      type: Twist
      surge: 0.0
      sway: 0.0
      depth: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: -15
transitions:
  - { trigger: found, source: [ROTATE_CLOCK, ROTATE_ANTICLOCK], dest: OK }
  - { trigger: fail, source: [ROTATE_CLOCK, ROTATE_ANTICLOCK], dest: FAILED }
  - { trigger: timeout, source: ROTATE_CLOCK, dest: ROTATE_ANTICLOCK }
  - { trigger: timeout, source: ROTATE_ANTICLOCK, dest: FAILED }
