initial: ROTATE_CLOCK
states:
  ROTATE_CLOCK:
    transition_event: 
      type: StringEvent
      topic_name: /stingray/demo
      data: "gate"
      count: 2
      trigger: ok
    timeout: 2
    action: 
      type: Move
      surge: 0.0
      sway: 0.0
      depth: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 15
  ROTATE_ANTICLOCK:
    transition_event: 
      type: StringEvent
      topic_name: /stingray/demo2
      data: "gate_anticlock"
      count: 2
      trigger: ok
    timeout: 15
    action: 
      type: Move
      surge: 0.0
      sway: 0.0
      depth: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: -15
transitions:
  - { trigger: ok, source: [ROTATE_CLOCK, ROTATE_ANTICLOCK], dest: OK }
  - { trigger: failed, source: [ROTATE_CLOCK, ROTATE_ANTICLOCK], dest: FAILED }
  - { trigger: timeout, source: ROTATE_CLOCK, dest: ROTATE_ANTICLOCK }
  - { trigger: timeout, source: ROTATE_ANTICLOCK, dest: FAILED }
