initial: ROTATE_CLOCK
states:
  ROTATE_CLOCK:
    transition_event: 
      type: StringEvent
      topic_name: /stingray/demo
      data: "gate"
      count: 2
      trigger: ok
    timeout: 60
    action: 
      type: Move
      # (surge, sway, depth)
      linear: (0, 0, 0)
      # (roll, pitch, yaw)
      angular: (0, 0, 15)
  ROTATE_ANTICLOCK:
    transition_event: 
      type: StringEvent
      topic_name: /stingray/demo2
      data: "gate_anticlock"
      count: 2
      trigger: ok
    timeout: 60
    action: 
      type: Move
      # (surge, sway, depth)
      linear: (0, 0, 0)
      # (roll, pitch, yaw)
      angular: (0, 0, 15)
transitions:
  - { trigger: ok, source: [ROTATE_CLOCK, ROTATE_ANTICLOCK], dest: OK }
  - { trigger: failed, source: [ROTATE_CLOCK, ROTATE_ANTICLOCK], dest: FAILED }
  - { trigger: timeout, source: ROTATE_CLOCK, dest: ROTATE_ANTICLOCK }
  - { trigger: timeout, source: ROTATE_ANTICLOCK, dest: FAILED }
